[tool.poetry]
name = "nephelaiio-pip"
version = "0.1.0"
description = ""
authors = ["Ted Cook <teodoro.cook@gmail.com>"]
readme = "README.md"
packages = [{include = "nephelaiio"}]

[tool.poetry.dependencies]
python = "^3.8"
ansible = "^6.6.0"
ansible-lint = "^6.8.6"
MarkupSafe = "2.0.1"
netaddr = "^0.8.0"
podman = "^4.3.0"
molecule = "^4.0.3"
molecule-podman = "^2.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
