---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: install helper packages
  package:
    name: "{{ pip_packages_helpers | default(pip_packages_helpers_default) }}"
    state: "{{ pip_packages_state }}"
  become: yes

- name: install pip
  easy_install:
    name: "{{ pip_packages | default(pip_packages_default) }}"
    state: "{{ pip_packages_state }}"
  when: ansible_os_family != "Archlinux"
  become: yes

- name: install pip
  package:
    name: "{{ pip_packages | default(pip_packages_default) }}"
    state: "{{ pip_packages_state }}"
  when: ansible_os_family == "Archlinux"
  become: yes
