---
- name: include variable overrides
  include_vars: "{{ item }}"
  vars:
    params:
      - "vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
      - "vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution | lower }}.yml"
      - "vars/{{ ansible_os_family | lower }}.yml"
      - "vars/default.yml"
  loop: "{{ q('first_found', params, skip=True) }}"

- block:

    - name: install epel
      yum:
        name: epel-release

    - name: install pip yum packages
      yum:
        name: "{{ pip_packages | default(pip_packages_default) }}"
        state: "{{ pip_packages_state }}"
        disable_gpg_check: yes

  when: ansible_os_family | lower == 'redhat'

- name: install pip deb packages
  apt:
    name: "{{ pip_packages | default(pip_packages_default) }}"
    state: "{{ pip_packages_state }}"
  when: ansible_os_family | lower == 'debian'

- name: install pips
  pip:
    name: "{{ pip_pip_names | default([]) }}"
    state: "{{ pip_pip_state | default('present') }}"
    executable: "{{ pip_executable | default(omit) }}"
  changed_when: false
