---
- name: set variable overrides
  ansible.builtin.set_fact:
    _pip_packages: "{{ pip_packages | default(pip_packages_default | sorted_get(overrides)) }}"
  vars:
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"

- name: install pip yum packages
  when: ansible_os_family | lower == 'redhat'
  block:

    - name: install epel
      ansible.builtin.yum:
        name: epel-release

    - name: install pip yum packages
      ansible.builtin.yum:
        name: "{{ _pip_packages }}"
        state: "{{ pip_packages_state }}"
        disable_gpg_check: yes


- name: install pip deb packages
  ansible.builtin.apt:
    name: "{{ _pip_packages }}"
    state: "{{ pip_packages_state }}"
  when: ansible_os_family | lower == 'debian'

- name: install pips
  ansible.builtin.pip:
    name: "{{ pip_pip_names | default([]) }}"
    state: "{{ pip_pip_state | default('present') }}"
  changed_when: false
