---
- name: include variable overrides
  include_vars: "{{ item }}"
  vars:
    params:
      - "vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
      - "vars/{{ ansible_distribution | lower }}.yml"
      - "vars/{{ ansible_os_family | lower }}.yml"
  loop: "{{ q('first_found', params, skip='yes') }}"

- name: install pip
  package:
    name: "{{ pip_packages | default(pip_packages_default) }}"
    state: "{{ pip_packages_state }}"

- name: install pip packages
  pip:
    name: "{{ pip_pip_names | default([]) }}"
    state: "{{ pip_pip_state | default('present') }}"
