---
- name: Set variable overrides
  ansible.builtin.set_fact:
    _pip_packages: "{{ pip_packages | default(_pip_packages_default) }}"
  vars:
    _pip_packages_default:  "{{ pip_packages_default | nephelaiio.plugins.sorted_get(overrides) }}"
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"

- name: Install pip yum packages
  when: ansible_os_family == 'RedHat'
  block:

    - name: Install epel
      ansible.builtin.yum:
        name: epel-release

    - name: Install pip yum packages
      ansible.builtin.yum:
        name: "{{ _pip_packages }}"
        state: "{{ pip_packages_state }}"
        disable_gpg_check: yes

- name: Install pip deb packages
  ansible.builtin.apt:
    name: "{{ _pip_packages }}"
    state: "{{ pip_packages_state }}"
  when: ansible_os_family == 'Debian'
