---
- name: converge

  hosts: all

  roles:
    - role: nephelaiio.pip

  pre_tasks:
    - name: update apt package cache
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
      changed_when: false
