---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: pip-default-instance01
    image: geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        pip_pip_names: docker
scenario:
  name: default
verifier:
  name: ansible
